---
deployment:
  tasks:
    - export DEPLOYPATH=/home/executive01/public_html # Add /<app_folder> if required
    - /bin cp * $DEPLOYPATH #copy all from root

# ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/executive01/public_html/
#     - /bin/cp index.html $DEPLOYPATH
#     - /bin/cp index.css $DEPLOYPATH

